### ISSUE TITLE
2023 Sep 20 meeting

### ISSUE THREAD

**Issue by qstommyshu** [InfiniView-AI/MotionMingle#1]
Location: ITB 121
Time: 2023-09-20 5:00PM - 5:30 PM

**Comment by jiaoa3** [comment]
Discussed the scope of the project

Why are we doing this?
Poor internet quality, then use this to help them to learn.

Video conferencing(webRTC to config)
The browser or delicate app is fine.

Three levels of ML:
Implementing existing project
Retrain ML Model, 
Build from scratch.


Successful expectation:
Leader
Be organized with docs
Manage timelines, have your milestone


What exactly needs to be made?
1. Interface students need to use to join the call, configure annotation
2. Instructor client: take in webcam and sound to server.


The mirror actually helped with prediction.

Optional: 
Analyze form action and see the form transition—auto caption to other videos that don’t have a caption for forms, etc.
Login
