### ISSUE TITLE
Team 15 VnV Report Review

### ISSUE THREAD

**Issue by stanreee** [InfiniView-AI/MotionMingle#114]
In the rubric, it says that information should not be unnecessarily repeated. The traceability between the two documents VnV plan and VnV report by referencing test name and IDs might be sufficient enough as opposed to writing all the details of the tests.

TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: 529178670873964d5116ac7a570b8a5e16ede219
