### ISSUE TITLE
Reflection doc

### ISSUE THREAD

**Issue by marischan888** [InfiniView-AI/MotionMingle#137]
Reflection document

**Comment by jiaoa3** [comment]
- [ ] SRS @marischan888 
- [ ] HA 
- [ ] Design Doc, MIS and MG 
- [ ] VnVplan 
- [ ] VnVReport

**Comment by jiaoa3** [comment]
- [ ] changes in VnV report @qstommyshu @KehaoHuang @yex33 
- [ ] Update Readme @jiaoa3 
- [ ] Code comments @qstommyshu 
- [ ] submit video link to a2l @qstommyshu 
- [ ] poster to print @yex33
