### ISSUE TITLE
Team 15 SRS Review: Imposed Technical Choices Issue

### ISSUE THREAD

**Issue by stanreee** [InfiniView-AI/MotionMingle#15]
The decision to include the selection of programming languages under **Imposed Technical Choices** (Python for machine learning, JavaScript/TypeScript for the web application frontend) does not seem to match the category’s criteria. As stated in the Meyer’s template, imposed choices are choices that bind the project to specific tools as a result of prior imposing external factors not based in the project itself (company regulations/policies, technical limitations, and as mentioned in the team’s SRS, academic contexts). These choices restrict the project, but are necessary as these external factors cannot be changed. 

The technical choice for Python and JavaScript/TypeScript is not a result of restrictions brought by imposing external factors, but is rather a result of industry standards and conventions, ones that do not necessarily need to be adhered to. As a result, including these choices in this section doesn’t seem appropriate, as it may bring up the possibility of unnecessarily restricting the project as mentioned before. A more appropriate section for these choices would be in “Required technology elements”, which already contains these technologies in the SRS. These are a list of expected technologies to be used in the design process, but aren’t a result of external imposing factors.

Team 15 TA: @Lyuyang0130

**Comment by qstommyshu** [comment]
resolved in commit: bbd38c25849a7dc8e02d19dc99b8b5e83b698ae2
