### ISSUE TITLE
Team 15 SRS Review: Missing FR for Audio Capability

### ISSUE THREAD

**Issue by jlangner15** [InfiniView-AI/MotionMingle#16]
In the Expected Benefits it was mentioned the system would be using real-time audio and video communication to elevate the Tai Chi learning experience however there is no mention of microphone audio capability within the functional requirements. The only hardware mentioned are webcams which do not always imply microphone audio capability for users. There should be instructor and user capability requirements and potentially a requirement to ensure microphone audio is working correctly. There is a reference to a camera and microphone within sect 5.5.2 Hardware Interfaces.

Team 15 TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
Resolved in:
[4a2917a](https://github.com/InfiniView-AI/MotionMingle/commit/4a2917a6777586eedbe54fbfdd8e42607500c029)
