### ISSUE TITLE
Team 15 SRS Review: Missing Reflection Appendix Section

### ISSUE THREAD

**Issue by CassieBaldin** [InfiniView-AI/MotionMingle#18]
It seems like your team SRS did not include the reflection section mentioned in the rubric and posted in the lecture called "Requirements Continued Continued". This reflection aims to answer the questions about what previous courses your team will look back on to complete your project, the skills your team will need to develop throughout your project, and how each member will work towards achieving these skills. I noticed that you have included what roles each team member will take on, but including this information in your appendix section for this project is important to see how you will grow in your technical and non-technical skills throughout the year. 
 
![image](https://github.com/InfiniView-AI/MotionMingle/assets/77757843/3cf24575-6daa-40fd-b5bf-982c363802f7)

Team 15 TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
Resolved in:
[4a2917a](https://github.com/InfiniView-AI/MotionMingle/commit/4a2917a6777586eedbe54fbfdd8e42607500c029)

**Comment by qstommyshu** [comment]
> Resolved in: [4a2917a](https://github.com/InfiniView-AI/MotionMingle/commit/4a2917a6777586eedbe54fbfdd8e42607500c029)

The reflection section is not added from the tagged commit.

**Comment by jiaoa3** [comment]
Resolved in:
4e2e4cec8281b73434b84ad8d7f1fedea034739c

**Comment by jiaoa3** [comment]
Resolved in:
4e2e4cec8281b73434b84ad8d7f1fedea034739c
