### ISSUE TITLE
Team 15 SRS Review: Certain Fit Criteria Not Measurable

### ISSUE THREAD

**Issue by edwardzhuang2001** [InfiniView-AI/MotionMingle#20]
Some fit criteria in your SRS document are not quantifiable/measurable. Fit criteria should binarily measure the requirement, i.e. it either passes or fails. However, there are a few criteria which are ambiguous and aren't exactly a pass-or-fail test.

Here is a list of requirements which should have stronger fit criteria:
- UH1: Users can complete common tasks within the system without extensive assistance. -- not measurable or quantifiable
- UH2: Elder users can perform basic tasks and navigate the system effectively after a short learning period. -- define what the short learning period is
- OE2: The platform functions correctly on major web browsers without significant deviations in performance or appearance. -- a specific metric for performance deviation should be defined
- OE3: The system shall run smoothly on standard personal computers or laptops equipped with a camera and optionally a microphone. -- should be defined
- MS1: Updates and maintenance tasks can be performed with minimal disruption to users. -- should be defined
- HS1: The hardware running the system is under normal temperature. -- should be defined
- HS2: Users feel comfortable using the system in various situations. -- not measurable or quantifiable

Fit criteria serve as a tool to verify whether or not your system fulfills your requirements and if they are not properly defined, you cannot have high-quality requirements. These metrics can always be changed at a later time to how you see fit.

Team 15 TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
Resolved in:
[4a2917a](https://github.com/InfiniView-AI/MotionMingle/commit/4a2917a6777586eedbe54fbfdd8e42607500c029)
