### ISSUE TITLE
Team 15 Hazard Analysis Review: Ambiguous Effects of Failure for ML Annotation Pipeline

### ISSUE THREAD

**Issue by edwardzhuang2001** [InfiniView-AI/MotionMingle#26]
For your ML Annotation Pipeline component, your two hazards have the same ambiguous effects of failure. I think you can identify more specifically what and how users' learning outcomes are impacted by the failure modes. For example, "latency in annotation", can have an effect of failure related to how the annotations do not sync up to the video. Overall I think there should be a bit more clarity in the effects of failure.

Team 15 TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: 68fbfae53dbfda0980220b49e69f32be92e37994
