### ISSUE TITLE
Team 15 Hazard Analysis Review: Missing Gloassry Entry 

### ISSUE THREAD

**Issue by Konadean** [InfiniView-AI/MotionMingle#27]
SFU was put into the glossary but STUN/TURN was not elaborated on in the same manner when it was used alongside SFU in 6.1.2 - PR2. Consider adding both for clarity and consistency. Additionally, since the glossary is short, consider changing the location to the beginning so the reader is familiar with the terms before encountering them.

TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: 68fbfae53dbfda0980220b49e69f32be92e37994
