### ISSUE TITLE
Team 15 Hazard Analysis Review: Some fit criteria could be more rigorous

### ISSUE THREAD

**Issue by CassieBaldin** [InfiniView-AI/MotionMingle#29]
Some of the fit criteria for requirements such as PR1, PR14 and HS2, do not seem sufficient enough. 

For PR1 and PR14, consider testing these requirements by ensuring that a certain percentage (ex. 95%) of user interactions and annotations meet this requirement, as it may be hard or unrealistic to expect 100% of interactions to be near-instantaneous or have less than the max delay at all times. 
For HS2, consider testing this requirement by using a user survey or rating to understand if your users are comfortable using the system.  

TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: 68fbfae53dbfda0980220b49e69f32be92e37994
