### ISSUE TITLE
Team 15 Hazard Analysis Review: PR Ambiguities

### ISSUE THREAD

**Issue by jlangner15** [InfiniView-AI/MotionMingle#30]
H1-2 addresses an unresponsive UI but PR1 does not consider how to appropriately address this delayed server side response. Consider adding a hazard analysis component to address server errors or delays and appropriately update H1-2 with such requirement.

For PR12 I think there should be a metric of the accuracy of annotation. This performance requirement does also not support the recommended action to send error forward to the front end. Consider adding another requirement to do so.

TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: 68fbfae53dbfda0980220b49e69f32be92e37994
