### ISSUE TITLE
Team 15 VnV Plan Review: Fit Criteria Not Very Specific

### ISSUE THREAD

**Issue by CassieBaldin** [InfiniView-AI/MotionMingle#36]
For the test NFR-T18, the output of the test is that "_the system operates without significant delays, errors, or crashes_", but does not specify in the test what is an acceptable range for the test error to be significant. In some of your other tests (like NFR-T14) you mention that the test will be considered successful if the delay is under "_MAX_DELAY_" which clearly sets a parameter for the test to stay within to be successful. Consider adding that to this test to make it more verifiable. 

TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: ed7d3ea9de2c8ecd01221f43b2461f2fbd82e2d2
