### ISSUE TITLE
Team 15 VnV Plan Review: 3.4 Verification and Validation Plan Consider Adding Mutation Tests

### ISSUE THREAD

**Issue by Konadean** [InfiniView-AI/MotionMingle#37]
As it stands right now, your team is relying on internal and external documentation review to validate your own tests. Adding in dedicated tests for your test like mutation tests for when they're actually implemented would be more of greater use in the future.

TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: ed7d3ea9de2c8ecd01221f43b2461f2fbd82e2d2
