### ISSUE TITLE
Team 15 VnV Plan Review LF1 Req and NFR-T1

### ISSUE THREAD

**Issue by jlangner15** [InfiniView-AI/MotionMingle#38]
NFR-T1 specifies functional interaction to test but LF-1 is purely non functional and does not specify any functionality. Consider adding in another functional requirement to specify this functionality or alter the NFR-T1 appropriately.

TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: ed7d3ea9de2c8ecd01221f43b2461f2fbd82e2d2
