### ISSUE TITLE
Team 15 VnV Plan Review: Specificity in VnV Team Roles

### ISSUE THREAD

**Issue by stanreee** [InfiniView-AI/MotionMingle#39]
I think it would be helpful to specify what kinds of testing strategies your teammates will employ for specific modules of the project. For example, full stack development testing might include some black box testing (when testing the frontend user interface), and the machine learning model testing could include unit testing, etc.

TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: ed7d3ea9de2c8ecd01221f43b2461f2fbd82e2d2
