### ISSUE TITLE
Development Planning Meeting, Thursday, Nov 16, 8:30 pm, Discord

### ISSUE THREAD

**Issue by qstommyshu** [InfiniView-AI/MotionMingle#45]
# Topics
- [x] Go over Vnv issues.
- [x] Assign development works
- [x] Plan development time line.

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by marischan888** [comment]
# Conclusions
1. Start resolving issues and revise documents after VnV feedback releases.
2. Combine and organize feedback from both peers and TA. Responsible for the portion of work you have done.
3. Do research on your own on client-server communication through WebRTC.
4. Research on adding annotations on local video streams (local webcam).
