### ISSUE TITLE
Supervisor Meeting, Scheduled, Wednesday, Dec 6, 5:00, Teams

### ISSUE THREAD

**Issue by yex33** [InfiniView-AI/MotionMingle#55]
# Topics
- [x] aiortc as backend server, more research needed to customize it for our project.
- [x] Frontend development has been started.
- [x] Started working on other course requirements: 1. Unit testing deployment pipeline 2. Document updates 

# Question
- [x] Do we have stakeholder group want to use our product? One of our course requirement is that we need to have stake holders to test our product and fill out a smaller survey to see how can we refine it.

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by qstommyshu** [comment]
Members in research lab will be off from Dec 23rd - Dec 25th
