### ISSUE TITLE
Development Planning Meeting, Thursday, Jan 4, 6:00 pm, Discord

### ISSUE THREAD

**Issue by qstommyshu** [InfiniView-AI/MotionMingle#56]
# Topics
- [x] Go over Problem Statement and Development Plan issues and fixes.
- [ ] ~Go over SRS issues and issues assignment~.
- [x] Development Planning.

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by yex33** [comment]
# Decisions
- WebRTC back: @jiaoa3 @yex33 @marischan888 
- Dummy unit tests and GitHub action @marischan888 
- WebRTC front: @qstommyshu 
- ML research: @KehaoHuang 
# Dev Plan issuses
- Ask Chris about plan to adapt role on discussion forum.
