### ISSUE TITLE
Deliverable Planning Meeting, Scheduled, Wednesday, September 27, 6:00 pm, Discord

### ISSUE THREAD

**Issue by yex33** [InfiniView-AI/MotionMingle#7]
# Topics
- [x] Go over ideas in the [Google Doc](https://docs.google.com/document/d/1H2GSj6eI4ijP67rO9DYVOC66j-r1Z9cpHPonfQtXaGk/edit?usp=sharing). Everyone grab topics in the SRS of interest. Breakdown tasks for writing SRS.
- [x] Report ML paper findings.
- [x] Sync up WebRTC research.
- [x] Decide on which team to review (we as the primary reviewer).
- [x] Reiterate on the responsibility to check issues and tasks. Importance of following the development plan, workflows. Means of communication. My expectations on communications.
- [x] Emphasize on primary goal of writing documents. Discussion on future work focus.
- [x] Plan for next meeting.
# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by qstommyshu** [comment]
see which team do we want to have for our primary reviewers.

**Comment by yex33** [comment]
> see which team do we want to have for our primary reviewers.

Sb

**Comment by yex33** [comment]
# Decisions Made
- Write the four books in the Meyer’s template in the following order: Environment -> Goals -> System -> Project
- [ ] @qstommyshu, @jiaoa3 Environment (due by next meeting)
- [ ] @marischan888, @KehaoHuang Goals (due by next meeting)
- [x] ~Ask Jason to review our capstone project.~ Pending reply
