### ISSUE TITLE
Team 15 Design Documentation Review: Module Guide Section 3.1 Links

### ISSUE THREAD

**Issue by CassieBaldin** [InfiniView-AI/MotionMingle#74]
In your module guide document, section 3.1 has links written in text to your SRS, Hazard Analysis, VnV Plan and MIS. To make these documents easier to find for people reading your module guide, you could consider changing them to direct links to these documents in your repo, similar to how you linked directly to your repo in your MIS document section 3. 

![image](https://github.com/InfiniView-AI/MotionMingle/assets/77757843/7371fc3a-5e00-4366-8bda-7a9e260a2821)

![image](https://github.com/InfiniView-AI/MotionMingle/assets/77757843/e0f93390-d316-426b-b5ed-c92d78261d7d)

TA: @Lyuyang0130

**Comment by jiaoa3** [comment]
resolved in: 0aee27fbd3930ea49d0d7649af6f0ce3c571eeea
