### ISSUE TITLE
Development Planning Meeting, Tuesday, Feb 6, 6:00 pm, Discord

### ISSUE THREAD

**Issue by qstommyshu** [InfiniView-AI/MotionMingle#89]
# Topics
- [x] Follow up on task progress
- [x] Discuss about supervisor meeting
- [x] Discuss about Rev0 demo
- [x] PR code reviews

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by jiaoa3** [comment]
# Conclusion
- [] update SRS based on current implementation Feb 10, 2024 at 10:00 am @qstommyshu @yex33 @marischan888 @KehaoHuang @jiaoa3 
- [] update progress to supervisors, if there is anything that has to be done by rev1
- [] practice rev0 presentation Feb 10, 2024 at 10:00 am @qstommyshu @yex33 @marischan888 @KehaoHuang @jiaoa3 
- [] set up video calls on different devices
- [] review current pr
