### ISSUE TITLE
Supervisor Meeting, Scheduled, Wednesday, Jan 24th, 5:00, Teams

### ISSUE THREAD

**Issue by qstommyshu** [InfiniView-AI/MotionMingle#90]
# Topics
- [x] discuss about future progress direction
- [x] update progress: 1. working on UI enhancement 2. unit testing 3. Connection with the summer Tai Chi project.

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by jiaoa3** [comment]
# Todo
-[ ] 2d HPE
-[ ] 3d HPE
-[ ] Semantic Segmentation, try to draw something over the person to show the effect
-[ ] ways to add titles
-[ ] different rooms with different annotations
